fix(Config): Ensure that invalid user config is handled gracefully
serverless/utils pull request #62
Opened 2020-12-17 11:31 UTC by pgrzesik

In progress

2020-12-17 11:42 UTC, pgrzesik commented on config.js
> +    return {};
Here, we could also once again try to get and return the global config via `getGlobalConfig` - it would allow us to ensure that if the global config was the problematic one, it was renamed and regenerated.

2020-12-17 12:29 UTC, medikoo commented
@pgrzesik very good questions

> what is the preferred convention when it comes to logging errors from this module

Actually it wasn't coined so far. 

So far in a Framework logs handling is quite primitive, we have general (always on) logs, and some more verbose logging (which provide more information that's helpful for debugging purposes) which can be turned on with `SLS_DEBUG=1`.

This is scheduled to be vastly improved by addressing https://github.com/serverless/serverless/issues/1720 (which has already proposed solution) - still that should not block us here.

For context of this util. I suggest that we first address https://github.com/serverless/serverless/issues/8444, but move the logging util to `log.js` in this package (and not to `lib/utils/log.js` as proposed in an issue).

Then for logging we can use that util here, and I'd log file syntax errors unconditionally as warnings (we color them in orange as here: https://github.com/serverless/serverless/blob/e32b7714253108f9078d2218e68c5994f20cde64/lib/classes/ConfigSchemaHandler/index.js#L78-L83)

> Do you think it would make sense to start introducing async approach in this module as well? 

Totally, and it can be done in all packages which were already upgraded to drop support for Node.js v6 (and that's all of them, apart `@serverless/test` which have that coming very soon with this PR: https://github.com/serverless/test/pull/59).

Here we can use it right away -> https://github.com/serverless/utils/blob/3234bdbd6a5e5b559757fa1cec670ffe9793393d/package.json#L101

> The only downside here is that it might trigger a "domino effect" 

It shouldn't, as async/await refactor does not change anything for consumer module (apart of fact that they also should have already dropped support for Node.js v6). 

Currently we refactor, on the go, when needed (trying to refactor everything, would be to big task to jump into). Also it's great to not mix such refactors with introduction of new functionalities. If we see that we could benefit from from async/await refactor it might be nice to first propose PR just with that refactor, and then follow with the functionality PR (although in our case where we merge via rebase, it's fine to split this work with individual commits in single PR)

Do you see such need here? I think all `config.js` functions are _sync_, and I'm not sure about changing that, as I think there's a reason in it. (e.g. it's fine to schedule writes sync way, without confirming that they went successful.. and in case of reads, it should I believe be read once and then accessed from cache)

> I'm not sure about renaming and generating a new local config file, because it would have to be pretty much the same as a global one which makes it redundant - 

In that case let's just show warning, and assume no config exists (so override errorneous one without backing it up).
It's really an edge case and most likely to be caused by manual play with config content.

2020-12-18 13:22 UTC, pgrzesik commented
Thanks @medikoo for answering all my questions. I've prepared the updated version, but I'd still would like to get your opinion on a few things, I've added comments directly on lines that I'm not sure about

2020-12-18 13:25 UTC, pgrzesik commented on config.js
> +    return {};
As mentioned above, here we have a bit tricky situation at the moment. With the current behavior, if someone uses `getConfig` and `rc` will throw an error, we're not renaming or generating new global config file, but rather issue a warning and return an empty config. At this point we're not sure if local or global config file was problematic. What we could potentially do is after catching the error, instead of `return {}`, we could still try to return the global config, via `return getGlobalConfig()`. What that would give us is the ability to rename and regenerate global config if it was in fact the one causing troubles. What is your opinion on that ?

2020-12-18 13:26 UTC, pgrzesik commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
Do you think we should also log `error.stack` in these situations? I believe we shouldn't do that for warnings, but wanted to get your opinion. (or maybe log them if `SLS_DEBUG` is set?)

2020-12-18 13:27 UTC, pgrzesik commented on test/config.js
> +    expect(stdoutData).to.include('Unable to read global config');
This is kinda iffy approach to testing logging, but I didn't come up with a better version that is able to mock/spy the `log` util with `sinon` - I'd love to hear your idea if you have a suggestion on how to improve it :100:

2020-12-18 13:31 UTC, medikoo commented on config.js
> +    return {};
> What we could potentially do is after catching the error, instead of return {}, we could still try to return the global config, via return getGlobalConfig().

I think it's a very good call, and in such case we would never override faulty config without backing it up first. I'd go for it

2020-12-18 13:35 UTC, medikoo commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
I think full stacks traces should apply only with `SLS_DEBUG`

Do you think in this case full stack trace would be helpful? (From those stacks you've observed will it give an additional aid exposing them in full ?) If not, I would not consider it. If yes, we may add that if `SLS_DEBUG` is set.

Also I would reword warning slightly:

```
User Configuration error: Cannot resolve config file: ${error.message}`
```

2020-12-18 13:36 UTC, medikoo commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
Also I wouldn't show warning or output anything if we redirect to global read, just let global read handle eventual error. That should make processing easier

2020-12-18 13:38 UTC, medikoo commented on test/config.js
> +    expect(stdoutData).to.include('Unable to read global config');
TBH I would just test, that util doesn't crash on errorneous file. I wouldn't confirm on warning logs output (we usually don't do that, as it's usually not involved in functionality outcome, and there are no good means to test human readable messages which are subject to constant improvements)

2020-12-18 13:42 UTC, medikoo commented on config.js
> +      } catch (renameError) {
We may skip error argument

2020-12-21 09:41 UTC, pgrzesik commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
I've tested it out and the stack traces are not really helpful so I've decided against including them. If there's a problem with accessing the file by `rc`, the file will be skipped silently, the only error that will bubble up is the JSON parsing error, but the stack trace doesn't add any value in this case as the error message already explains what happened

2020-12-21 13:48 UTC, medikoo commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
> I've tested it out and the stack traces are not really helpful so I've decided against including them.

How exactly message with a stack trace looks?

2020-12-21 13:59 UTC, medikoo requested changes
Looks great @pgrzesik ! I have just one minor suggestion towards warnings wording

2020-12-21 13:59 UTC, medikoo commented on config.js
> +    });
Let's maybe reword `error` to `warning` (as we do not fail, and logically we treat it as warning).

I remember when first we were reporting configuration validation errors as _errors_ and most of the users assumed things got broken

2020-12-21 14:03 UTC, medikoo commented on config.js
> +    log(`Unable to read config due to ${rcError.message} error`, { color: 'orange' });
@pgrzesik Ignore above message (I've read _I've tested it out and the stack traces are really helpful_)

2020-12-22 12:06 UTC, medikoo approved these changes
Looks great! 👍

2020-12-22 15:09 UTC, merged