feat(Config): Introduce new config resolution
serverless/utils pull request #70
Opened 2021-01-23 17:26 UTC by pgrzesik

Notifications tests had to be adjusted because they became nondeterministic - in some cases, the `lastShown` date for two notifications was the same and not the one that was expected was returned.

It introduces the following breaking changes:
- Removed `getGlobalConfig` from API
- removed support for all `rc`-discoverable files
- update not always modify only global config (if local is present, it's the one that will get updated)

Closes: #69

2021-01-25 07:38 UTC, pgrzesik commented on test/config.js
> +      await fs.promises.mkdir('local');
The reason for that construct present in multiple tests is the fact that we're mocking both `homedir` and `cwd` to a temporary directory, which means that both local and global config has the same location in these scenarios. I'd love to hear feedback on how to potentially improve that in the scope of these tests

2021-01-25 13:05 UTC, medikoo requested changes
Looks really good! It's great to see so extensive testing (after all it's a very sensitive functionality)

I have just few comments. Let me know

2021-01-25 13:05 UTC, medikoo commented on test/config.js
> +  });
I take, it's to test, the `updated_at`, but isn't it overkill? Can't we simply do `setTimeout(.., 10)` and confirm that `updated_at` was updated (?) If it appears as needed, maybe it'll be nicer to mock timers only for tests where we test that functionality and not whole test file (?)

2021-01-25 13:05 UTC, medikoo commented on test/config.js
> +      await fs.promises.mkdir('local');
I think you've taken very good approach, I cannot think of anything better 👍

2021-01-25 14:34 UTC, pgrzesik commented on config.js
> +  return storeConfig(config, configPath, { updated: true });
I think we can skip returning anything from `storeConfig` :+1:

2021-01-25 14:36 UTC, pgrzesik commented on config.js
> +    if (options.updated) {
I wanted to keep previous behavior when on default global config creation `updated_at` was not populated but I'm fine with updating it unconditionally. What do you think?

2021-01-25 14:37 UTC, pgrzesik commented on config.js
> +  const user = get(['users', config.userId, 'dashboard'], config);
definitely, I totally missed that when moving functionality from `platform-sdk`

2021-01-25 14:38 UTC, medikoo commented on config.js
> +    if (options.updated) {
I would update it unconditionally. I think there's no valid reason to be conditional here.

2021-01-25 14:39 UTC, pgrzesik commented on config.js
> +  } catch (error) {
Unless I'm missing something, in error scenario we will always return a default config thanks to `return createDefaultGlobalConfig()` at the end of this function. Am I missing something here?

2021-01-25 14:43 UTC, pgrzesik commented on test/process-backend-notification-request.js
> +    clock = sinon.useFakeTimers(Date.now());
I've tried to clarify that on lines 27-28. Essentially, it turned out that after refactoring, new config resolution is faster than `rc` and this test started to fail from time to time. After inspection, it was caused by the fact that some of the notifications were emitted almost at the exact same time, which caused them to have the same `lastShown` value. That in turn resulted in the functionality selecting the next notification to be emitted to be resolved incorrectly (I've observed situations where `CODE0A` was selected instead of `CODE0C` because they had the same `lastShown` date.

2021-01-25 14:44 UTC, pgrzesik commented on test/config.js
> +  });
I agree, it might be a bit of an overkill here. I'll adjust it :+1:

2021-01-25 14:45 UTC, medikoo commented on config.js
> +  } catch (error) {
Ah yes, indeed, I didn't look carefully. Ignore this comment

2021-01-25 14:52 UTC, pgrzesik commented on config.js
> +    if (options.updated) {
updated :+1:

2021-01-25 15:00 UTC, pgrzesik commented on test/process-backend-notification-request.js
> +    clock = sinon.useFakeTimers(Date.now());
I think `wait(1)` here makes sense and is definitely enough :+1: I might be heavily biased myself due to my background in Python, where mocking time is much more common practice. I've changed to the suggested approach :+1:

2021-01-26 10:48 UTC, medikoo requested changes
Looks great @pgrzesik ! I've posted just a few minor suggestions

2021-01-26 10:48 UTC, medikoo commented on config.js
> +  return storeConfig(config, configPath);
As now `storeConfig` doesn't return anything, I think we need to return result of `getConfig` here

2021-01-26 10:48 UTC, medikoo commented on config.js
> +  return storeConfig(config, configPath);
Same here

2021-01-26 12:05 UTC, medikoo approved these changes
Great job! 👍

2021-01-26 13:36 UTC, merged