feat: Add account-related methods
serverless/utils pull request #73
Opened 2021-01-27 10:58 UTC by pgrzesik

Adds account-related methods as described in linked issue. 

I've made a decision to depend on injected `sdk` instance, which is supposed to be an instance of `ServerlessSDK` from `@serverless/platform-client` library. It is aimed to be temporary solution, which will be cleaned up when `components`, `enterprise-plugin` and `serverless` will be moved into one repository. 

Closes: #72

2021-01-27 10:59 UTC, pgrzesik commented on account.js
> +const logout = () => {
Corresponding method from `platform-sdk`: https://github.com/serverless/platform-sdk/blob/master/src/logout/index.js#L10

2021-01-27 11:00 UTC, pgrzesik commented on account.js
> +const logout = () => {
I've made a decision to drop manipulation of `enterprise` section as it seems to be "legacy" part of the configuration - please correct me if I'm wrong here.

2021-01-27 11:00 UTC, pgrzesik commented on account.js
> +const refreshToken = async (sdk) => {
Corresponding method in `platform-sdk`: https://github.com/serverless/platform-sdk/blob/master/src/login/refreshToken.js#L6

2021-01-27 11:01 UTC, pgrzesik commented on account.js
> +const refreshToken = async (sdk) => {
I've decided to skip saving `expiresAt` field as it seems we're not using it anywhere and the expiration date is always derived from `idToken` anyway. Please let me know if you feel like we're still supposed to save it

2021-01-27 11:02 UTC, pgrzesik commented on account.js
> +  const tokens = await sdk.session.refreshToken(loggedInUser.refreshToken);
Corresponding method from `platform-client`: https://github.com/serverlessinc/platform/blob/master/sdk/src/index.js#L79

2021-01-27 11:02 UTC, pgrzesik commented on account.js
> +    const createdAccessKeyResponse = await sdk.accessKeys.create(
Corresponding method from `platform-client`: https://github.com/serverlessinc/platform/blob/master/sdk/src/index.js#L461

2021-01-27 11:03 UTC, pgrzesik commented on account.js
> +const getAccessKeyForOrg = async (sdk, orgName, title) => {
Corresponding method in `platform-sdk`: https://github.com/serverless/platform-sdk/blob/master/src/accessKeys/accessKeys.js#L37

2021-01-27 14:24 UTC, medikoo requested changes
Looks great @pgrzesik 👍 I have just few minor concerns

2021-01-27 14:24 UTC, medikoo commented on account.js
> +    throw new Error('Could not find logged in user. Please log in.');
I take this signals _programmer_ error (not something we envision with correct utils usage). In such case, it'll be better to shorten message to simply: `Could not find logged in user` (_"Please log in."_ suggests it's intended to be presented in valid scenarios to users, and such error should not be thrown with regular `Error` constructor)

2021-01-27 14:24 UTC, medikoo commented on account.js
> +  );
Same here, it'll be good clarify if it's a _programmer_ or _user_ error, and configure it as one.

2021-01-28 09:41 UTC, pgrzesik commented on account.js
> +  if (process.env.SERVERLESS_ACCESS_KEY) {
That's a good question - the potential problem here is that all clients of that method would have to account for that fact and implement a potential wrapper that will first check if there's a value injected via `SERVERLESS_ACCESS_KEY` env var.

2021-01-28 09:41 UTC, pgrzesik commented on account.js
> +const getAccessKeyForOrg = async (sdk, orgName, title) => {
good call :+1:

2021-01-28 09:44 UTC, pgrzesik commented on account.js
> +    throw new Error('Could not find logged in user. Please log in.');
Great point - how would you go about it then? I've adapted to the approach that we currently have in `platform-sdk`, where such errors are thrown with instructions for users to `logout/login` (reference: https://github.com/serverless/platform-sdk/blob/master/src/accessKeys/accessKeys.js#L66) and aren't being handled in any specific way.

2021-01-28 09:44 UTC, pgrzesik commented on account.js
> +    const createdAccessKeyResponse = await sdk.accessKeys.create(
good call :+1:

2021-01-28 09:45 UTC, pgrzesik commented on account.js
> +  );
Please see my other comment about approach to errors

2021-01-28 09:47 UTC, pgrzesik commented
Thanks @medikoo for a review :bow: I've started thinking again about proper placement for `getAccessKeyForOrg` method. A few of your suggestions make a lot of sense (about env var handling and error handling), however, that would require the clients of this method to create yet another wrapper for it to provide client specific functionality (honoring env var for example) - which makes me think - are `serverless/utils` a proper place for this method? The only client at the moment for it will be `enterprise-plugin`, and if we're going to have to wrap it there anyway, maybe we should just implement it directly in plugin? What do you think?

2021-01-28 12:42 UTC, medikoo commented on account.js
> +    throw new Error('Could not find logged in user. Please log in.');
If those errors handle valid scenarios, and are intended to be host messages to be shown to users. Then they should be thrown with `ServerlessError` (in such case we should move this utility to this repository).

If those errors are to point errors in our internal flow (and by no means can be triggered by valid user flow), then they should not contain any user facing messaging, but simply state what's wrong.

2021-01-28 12:44 UTC, medikoo commented on account.js
> +    throw new Error('Could not find logged in user. Please log in.');
So my recommendation depends on what kind of error it is (_user_ or _programmer_?). It's not perfectly clear to me

2021-01-28 12:47 UTC, medikoo commented
> The only client at the moment for it will be enterprise-plugin, and if we're going to have to wrap it there anyway, maybe we should just implement it directly in plugin? What do you think?

if it's just for `enterprise-plugin` I would probably keep there.

Otherwise this _utils_ project is more a _common_ (not really utils) project. It's to host all functionalities that are used by more than one of our CLI packages.

Relying on env vars here is fine. I was just questioning util design, but I don't know all the places where it's used.

2021-01-28 13:34 UTC, pgrzesik commented on account.js
> +    throw new Error('Could not find logged in user. Please log in.');
Thank you and sorry for not being clear. These errors can be triggered by valid flow as far as I'm concerned and they should be visible to users. However, at this point I think it makes more sense to move this function to `enterprise-plugin` as it's going to be the only client. I'll remove it from this PR, sorry for the confusion

2021-01-28 13:42 UTC, pgrzesik commented
Thanks for a review, as mentioned, I've decided to remove `getAccessKeyForOrg` from this PR for now and move the implementation directly to `enterprise-plugin`.

2021-01-28 19:48 UTC, medikoo approved these changes
Looks great 👍

2021-01-28 22:02 UTC, merged