feat: Add support for recording `duration` in `StepHistory`
serverless/utils pull request #92
Opened 2021-07-19 12:01 UTC by pgrzesik

As that utils needs to be reused across two separate directories, I've decided that it will make the most sense to have it in this repository.

2021-07-19 14:19 UTC, medikoo requested changes
@pgrzesik looks very promising, still I've proposed some changes which I think may improve the interface. Let me know what you think

2021-07-19 14:19 UTC, medikoo commented on inquirer/prompt-with-history.js
> +  if (answer && trimAnswer) {
I would drop `trimAnswer` option.

Let's trim unconditionally whenever `typeof answer === 'string'`

2021-07-19 14:19 UTC, medikoo commented on inquirer/prompt-with-history.js
> +    await inquirer.prompt({
Do we configure all questions via `prompt` ?

2021-07-19 14:19 UTC, medikoo commented on inquirer/prompt-with-history.js
> +    typeof answer === 'string' && answer.startsWith('_') ? answer : '_user_provided_';
I found `_user_provided_` slightly confusing when user was chosing from options we presented (e.g. in case of provider case.

Maybe we can do `_user_input_` on text input and `_user_choice_` on choice from a list (I think we can detect wether that's select or input by `type` option)

---

I'm not pushing for this, as it'll break consistency with old data, but if not that harmful I think it'll be nice improvement.

2021-07-19 14:19 UTC, medikoo commented on telemetry.js
> +    return super.set(key, newValueWithTimestamp);
Maybe it would be nicer to replace `set`, with `start` and `finalize` methods? which would be dedicated for what we're doing here.
I'm afraid that logic as proposed can be error prone, e.g. if we call `set` three times by accident there'll be wrong results, and we we wouldn't be able to detect that by looking at data.

ofc `set` will have to stay, at least in context of this major.

2021-07-19 14:19 UTC, medikoo commented on telemetry.js
> +      newValueWithTimestamp.duration = timestamp - oldValueWithTimestamp.timestamp;
Instead  would probably introduce `started_at` and `finalized_at` properties, and for mixpanel resolve `duration` from that. It feels more atomic.

2021-07-19 15:13 UTC, pgrzesik commented on telemetry.js
> +    return super.set(key, newValueWithTimestamp);
Yeah, I wasn't sure about the original approach as it is indeed error prone. I've changed to the proposed approach but I'm still wondering - how should we behave when `finalize` is called without calling `start` first? I've opted to just ignore such situation and not fail, but the output will be missing `startedAt` property. What do you think we should do here?

2021-07-19 15:13 UTC, pgrzesik commented on telemetry.js
> +      newValueWithTimestamp.duration = timestamp - oldValueWithTimestamp.timestamp;
Sounds good - i've went with `startedAt` and `finalizedAt`

2021-07-19 15:13 UTC, pgrzesik commented on inquirer/prompt-with-history.js
> +    typeof answer === 'string' && answer.startsWith('_') ? answer : '_user_provided_';
Good idea, I think this is a good moment to introduce such change and it nicely differentiates between two types of answers. :+1:

2021-07-19 15:15 UTC, pgrzesik commented on inquirer/prompt-with-history.js
> +    await inquirer.prompt({
Yes, in all instances in order to configure a question we use `inquirer.prompt`. There are minor cases where we use `confirm` helper that uses `prompt` underneath, but the usage is not consistent and we only use it in a few places so I'm going to remove it (it stays in `utils` in context of this major as it could be a breaking change to remove it)

2021-07-19 15:15 UTC, pgrzesik commented on inquirer/prompt-with-history.js
> +  if (answer && trimAnswer) {
changed :+1: good suggestion

2021-07-19 15:41 UTC, medikoo reviewed
@pgrzesik looks great. I have just one suggestion towards `finalize` to make it simpler (and do not handle scenarios where `start` wasn't called (that shouldn't be the case, and we can fall then into programmer error)

2021-07-19 15:41 UTC, medikoo commented on telemetry.js
> +      ...previousValueObject,
I would rather keep old object intact. We can simply assign properties on retrieved object.

We may also skip `set`, and assume unconditionally that `super.get(key)` will return object. If it wouldn't we can assume programmer error (and it's fine to crash then with ugly error which will be result of e.g. assigning to `undefined`)

2021-07-19 16:00 UTC, medikoo commented on telemetry.js
> +      timestamp,
I think we don't need `timestamp` anymore (?)

2021-07-20 08:23 UTC, pgrzesik commented on telemetry.js
> +      timestamp,
We might remove `timestamp`, but I think at this point we should consider upgrading the major version of `utils`, as well as bumping the major version of `dashboard-plugin`, which we might have to do anyway, as the `stepHistory` is being passed from the Framework and if `dashboard-plugin` will be in higher version, it might try to call `start/finalize` methods that are not available on older `StepHistory` instance from the Framework. Do you think we should clean that up at this point?

2021-07-20 10:22 UTC, medikoo commented on telemetry.js
> +      timestamp,
As discussed offline, probably best way is to move this logic into Framework. It'll also prevent any of such issues in a future

2021-07-20 10:47 UTC, medikoo approved these changes
Looks great 👍

2021-07-20 13:49 UTC, merged